# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIkbbn4LZ06xf3fjKev1gX0odOCuvnVp
"""

import pandas as pd

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/datasets/iris.data')

